- name: Install package manager utilities
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - software-properties-common

- name: Install TERM screen-256color-bce
  apt:
    name: ncurses-term
    state: present
    update_cache: true

- name: Install enhanced editor
  apt:
    name: vim
    state: present
    update_cache: true

- name: Install process observation tools
  apt:
    name: htop
    state: present
    update_cache: true

- name: Install web tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - curl
      - wget

- name: Install shell completion
  apt:
    name: bash-completion
    state: present
    update_cache: true

- name: Install Python pip
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - python-pip
      - python3-pip

- name: Install BSD commandline tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - bsdutils
      - bsdmainutils
