dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint --strict -c .yamllint .
  ansible-lint -x 106 .
  flake8

platforms:
  - name: instance
    image: debian:buster
    dockerfile: Dockerfile.j2
    override_command: false
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      verbosity: 1

verifier:
  name: testinfra
